version: "3"

services:
  app:
    build: .
    command: npm start
    ports: 
      - "3001:3001"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  
  db:
    image: 'mongo'
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db